package com.assurance.creditaccessor.creditscoregeneration.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2016-10-06T16:22:00.173-05:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://service.creditscore.creditbureau.com/", name = "CreditScoreService")
@XmlSeeAlso({ObjectFactory.class})
public interface CreditScoreService {

    @WebMethod
    @RequestWrapper(localName = "getCreditScoreBySSN", targetNamespace = "http://service.creditscore.creditbureau.com/", className = "com.assurance.creditaccessor.creditscoregeneration.webservice.GetCreditScoreBySSN")
    @ResponseWrapper(localName = "getCreditScoreBySSNResponse", targetNamespace = "http://service.creditscore.creditbureau.com/", className = "com.assurance.creditaccessor.creditscoregeneration.webservice.GetCreditScoreBySSNResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getCreditScoreBySSN(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
